# Generated by Django 3.0.5 on 2020-04-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_name', models.CharField(default='', max_length=50)),
                ('subject_name', models.CharField(default='', max_length=100)),
                ('chapter_name', models.CharField(max_length=300)),
                ('teacher_name', models.CharField(default='', max_length=100)),
                ('link_name', models.URLField(default='')),
            ],
        ),
    ]
