# Generated by Django 3.0.5 on 2020-04-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=300)),
                ('teacher_name', models.CharField(max_length=100)),
                ('link_name', models.URLField()),
                ('date_time', models.DateTimeField()),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
