# Generated by Django 3.0.5 on 2020-04-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_auto_20200410_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='done',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='Class_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='file_field',
            field=models.FileField(default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='subject_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
