# Generated by Django 3.0.5 on 2020-04-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_auto_20200411_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='link_name',
            field=models.URLField(default=''),
        ),
    ]
