# Generated by Django 3.0.5 on 2020-04-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0004_auto_20200411_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='file_field',
            field=models.FileField(default='', upload_to='static/images'),
        ),
    ]
