# Generated by Django 3.0.5 on 2020-04-12 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0005_auto_20200411_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='file_field',
        ),
    ]
